name: "Submit a Bulk Claim Services"

secrets:
  github_actor:
    environment: GITHUB_ACTOR
  github_token:
    environment: GITHUB_TOKEN

include:
  - laa-data-claims-api/docker-compose.yml
  - laa-data-claims-event-service/docker-compose.yml
  - laa-submit-a-bulk-claim/docker-compose.yaml
  - laa-amend-a-claim/docker-compose.yml
